[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[phases.build]
# Install dependencies
cmds = [
    "python3 -m venv venv",
    "source venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "venv/bin/python manage.py runserver 0.0.0.0:8000"
